spring:
  application:
    name: tpap-service

server:
  port: 8080

payments:
  tpap:
    psp-base-url: http://localhost:8081

logging:
  pattern:
    console: "%d{ISO8601} %-5level [%X{correlationId}] %logger - %msg%n"

# ---
# spring:
#   config.activate.on-profile: docker

# payments:
#   tpap:
#     psp-base-url: http://psp:8081
