spring:
  application:
    name: npci-switch-service
  datasource:
    url: jdbc:h2:mem:npci;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8082

payments:
  npci:
    bank-a-base-url: http://localhost:8083
    bank-b-base-url: http://localhost:8084

logging:
  pattern:
    console: "%d{ISO8601} %-5level [%X{correlationId}] %logger - %msg%n"
