spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/npci
    username: postgres
    password: admin
  flyway:
    enabled: true

payments:
  npci:
    bank-a-base-url: http://localhost:8083
    bank-b-base-url: http://localhost:8084

server:
  port: 8082
